# code: language=ansible
---
- name: Set up Development Environment
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Debug ansible_user
      ansible.builtin.debug:
        msg: "Current user is {{ ansible_user }}"

    - name: Debug ansible_os_family
      ansible.builtin.debug:
        msg: "OS Family is {{ ansible_os_family }}"

  roles:
    - role: debian
      become: true
      when: ansible_os_family == "Debian"
    - role: arch
      become: true
      when: ansible_os_family == "Archlinux"
    - role: macos
      become: true
      when: ansible_os_family == "Darwin"
    - role: windows
      become: true
      when: ansible_os_family == "Windows"
    - role: common
