---
- name: Set up Development Environment
  hosts: localhost
  gather_facts: yes

  pre_tasks:
    - name: Gather current user facts
      set_fact:
        current_user: "{{ ansible_facts['env']['USER'] | default(ansible_facts['user']) }}"

    - name: Debug current_user
      debug:
        msg: "Current user is {{ current_user }}"

  roles:
    - common
    - role: debian
      when: ansible_facts['os_family'] == "Debian"
    - role: fedora
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "Fedora"
    - role: arch
      when: ansible_facts['os_family'] == "Archlinux"
    - role: macos
      when: ansible_facts['os_family'] == "Darwin"
    - role: windows
      when: ansible_facts['os_family'] == "Windows"
