# code: language=ansible
---
- name: Set up Development Environment
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Debug ansible_user
      ansible.builtin.debug:
        msg: "Current user is {{ ansible_user }}"

    - name: Fail if ansible_user is root
      ansible.builtin.fail:
        msg: "Please run this playbook as a non-root user"
      when: ansible_user == "root"

    - name: Debug ansible_os_family
      ansible.builtin.debug:
        msg: "OS Family is {{ ansible_os_family }}"

    - name: Fail if OS is not Debian
      ansible.builtin.fail:
        msg: "This playbook only supports Debian-based systems"
      when: ansible_os_family != "Debian"

  roles:
    - role: debian
      become: true
      tags: os
      when: ansible_os_family == "Debian"

    - role: common
      tags: common

    - role: clojure
      tags: clojure
    - role: exercism
      tags: exercism
    - role: java
      tags: java
    - role: zsh
      tags: zsh

  # Maybe Later
  # - role: arch
  #   when: ansible_os_family == "Archlinux"
  #
  # - role: macos
  #   when: ansible_os_family == "Darwin"
  #
  # - role: windows
  #   when: ansible_os_family == "Windows"
