# code: language=ansible
---
- name: Install pipx
  ansible.builtin.package:
    name: pipx
    state: present

# - name: Install ansible with pip3
#   ansible.builtin.command:
#     cmd: pip3 install ansible
#     creates: /usr/local/bin/ansible

# - name: Ensure pipx is in PATH
#   become: false
#   ansible.builtin.command:
#     cmd: pipx ensurepath
#   when: not ansible_local.pipx.path
#   changed_when: false

- name: Install ansible-dev-tools with pipx
  become: false
  ansible.builtin.command:
    cmd: pipx install ansible-dev-tools
    creates: /home/{{ ansible_user }}/.local/bin/adt
