# code: language=ansible
---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # Cache is considered valid for 1 hour

- name: Upgrade all apt packages
  become: true
  ansible.builtin.apt:
    upgrade: dist

- name: Install basic packages
  become: true
  ansible.builtin.apt:
    name:
      - ack
      - autoconf
      - automake
      - build-essential
      - curl
      - emacs
      - git
      - make
      - vim
      - wget
    state: present
