# code: language=ansible
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # Cache is considered valid for 1 hour

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the machine if required
  ansible.builtin.reboot:
  when: reboot_required.stat.exists

- name: Install basic packages
  ansible.builtin.apt: # Using apt for consistency in Debian/Ubuntu environments
    name:
      - ack
      - autoconf
      - automake
      - build-essential
      - curl
      - git
      - htop
      - make
      - software-properties-common
      - tree
      - vim
      - wget
    state: present
