# code: language=ansible
---
- name: Ensure required packages
  become: true
  ansible.builtin.package:
    name:
      - rlwrap
    state: present

- name: Check for a java runtime
  ansible.builtin.command: java -version
  changed_when: false
  failed_when: false

- name: Install Clojure using mise
  ansible.builtin.import_role:
    name: mise
  vars:
    mise_library_name: clojure
    mise_library_version: 1.11
