# code: language=ansible
---
- name: Install zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Download oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{ ansible_user }}/bin/oh-my-zsh.sh
    mode: "0644"

- name: Run the oh-my-zsh install script
  ansible.builtin.command: |
    ./oh-my-zsh.sh --unattended
  args:
    chdir: /home/{{ ansible_user }}/bin
    creates: /home/{{ ansible_user }}/.oh-my-zsh

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Copy alias.zsh to oh-my-zsh custom dir
  ansible.builtin.copy:
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/
    mode: "0644"
    src: alias.zsh

- name: Copy path.zsh to oh-my-zsh custom dir
  ansible.builtin.copy:
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/
    mode: "0644"
    src: path.zsh

- name: Copy mise.zsh to oh-my-zsh custom dir
  ansible.builtin.copy:
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/
    mode: "0644"
    src: mise.zsh
