# code: language=ansible
---
- name: List installed plugins {{ mise_library_name }}
  ansible.builtin.command: |
    {{ mise_command }} plugins ls --user -c
  register: mise_plugins
  changed_when: false

- name: Ensure the plugin is installed {{ mise_library_name }}
  ansible.builtin.command: |
    {{ mise_command }} plugins install {{ mise_library_name }} --yes
  register: mise_install_plugin
  when: mise_plugins.stdout is not search(mise_library_name)
  changed_when: mise_install_plugin.stdout is search("installed")

- name: List installed libraries
  ansible.builtin.command: |
    {{ mise_command }} ls -gi
  register: mise_libs
  changed_when: false

- name: Check if library is installed {{ mise_library_name }}
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      {{ mise_command }} ls -gi | grep -Eq "{{ mise_library_name }}\\s+{{ mise_library_version }}"
    executable: /bin/bash
  register: mise_library_installed
  failed_when: false
  changed_when: false

- name: Ensure the library is installed {{ mise_library_name }}
  ansible.builtin.command: |
    {{ mise_command }} use -g {{ mise_library_name }}@{{ mise_library_version }}
  register: mise_install_library
  when: mise_library_installed.rc != 0
  changed_when: mise_install_library.stdout is search("installed")
