# code: language=ansible
---
- name: Ensure the exercism directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/exercism
    state: directory
    mode: "0755"

- name: Download and unpack the latest release archive
  ansible.builtin.unarchive:
    src: |
      https://github.com/exercism/cli/releases/download/v3.4.0/exercism-3.4.0-linux-x86_64.tar.gz
    dest: /home/{{ ansible_user }}/exercism
    remote_src: true

- name: Copy the executable to ~/bin
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/exercism/exercism
    dest: /home/{{ ansible_user }}/bin/exercism
    mode: "0755"
