# code: language=ansible
---
- name: Ensure required packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - rlwrap

- name: Check for a java runtime
  ansible.builtin.command: java -version
  register: java_version
  changed_when: false
  failed_when: false

- name: Check if clojure plugin is installed
  ansible.builtin.command: |
    ~/.local/bin/mise plugins ls
  register: mise_plugins_ls
  changed_when: false

- name: Add the clojure plugin to mise
  ansible.builtin.command: |
    ~/.local/bin/mise plugins install clojure --yes
  register: mise_install_clojure
  when: "'clojure' not in mise_plugins_ls.stdout"
  changed_when: mise_install_clojure.rc == 0

- name: Install Clojure 1.11 using mise
  ansible.builtin.include_role:
    name: mise_installer
  vars:
    library_name: clojure
    library_version: 1.11
