# code: language=ansible
---
- name: Ensure the bin directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/bin
    state: directory
    mode: "0755"

- name: Set up mise
  ansible.builtin.include_tasks: mise.yml
